/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. All request and response parameters are case sensitive. 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PushMethod
    /// </summary>
    [DataContract(Name = "PushMethod")]
    public partial class PushMethod : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PushMethod" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PushMethod() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PushMethod" /> class.
        /// </summary>
        /// <param name="type">The push method type corresponding to the URI supported by the Token Requestor. The array is absent if the Token Requestor does not support MDES Token Connect. __Max Length:__ 32 Possible values are:  * \&quot;ANDROID\&quot;: The URI is an Android app intent.  * \&quot;IOS\&quot;: The URI is an iOS app intent.  * \&quot;WEB\&quot;: The URI is a browser URL.  (required).</param>
        /// <param name="uri">The URI to open the Token Requestor&#39;s application or website. Please refer to the Issuer Interface Implementation Guide for the detail of how to send the data to the Token Requestor. __Max Length:__ 128  (required).</param>
        public PushMethod(string type = default(string), string uri = default(string))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for PushMethod and cannot be null");
            }
            this.type = type;
            // to ensure "uri" is required (not null)
            if (uri == null)
            {
                throw new ArgumentNullException("uri is a required property for PushMethod and cannot be null");
            }
            this.uri = uri;
        }

        /// <summary>
        /// The push method type corresponding to the URI supported by the Token Requestor. The array is absent if the Token Requestor does not support MDES Token Connect. __Max Length:__ 32 Possible values are:  * \&quot;ANDROID\&quot;: The URI is an Android app intent.  * \&quot;IOS\&quot;: The URI is an iOS app intent.  * \&quot;WEB\&quot;: The URI is a browser URL. 
        /// </summary>
        /// <value>The push method type corresponding to the URI supported by the Token Requestor. The array is absent if the Token Requestor does not support MDES Token Connect. __Max Length:__ 32 Possible values are:  * \&quot;ANDROID\&quot;: The URI is an Android app intent.  * \&quot;IOS\&quot;: The URI is an iOS app intent.  * \&quot;WEB\&quot;: The URI is a browser URL. </value>
        /// <example>WEB</example>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string type { get; set; }

        /// <summary>
        /// The URI to open the Token Requestor&#39;s application or website. Please refer to the Issuer Interface Implementation Guide for the detail of how to send the data to the Token Requestor. __Max Length:__ 128 
        /// </summary>
        /// <value>The URI to open the Token Requestor&#39;s application or website. Please refer to the Issuer Interface Implementation Guide for the detail of how to send the data to the Token Requestor. __Max Length:__ 128 </value>
        /// <example>http://www.tokenrequestor1.com/pushtoken</example>
        [DataMember(Name = "uri", IsRequired = true, EmitDefaultValue = true)]
        public string uri { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PushMethod {\n");
            sb.Append("  type: ").Append(type).Append("\n");
            sb.Append("  uri: ").Append(uri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
