/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;


namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RequestActivationMethodsResponseSchema
    /// </summary>
    [DataContract(Name = "requestActivationMethodsResponseSchema")]
    public partial class RequestActivationMethodsResponseSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestActivationMethodsResponseSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RequestActivationMethodsResponseSchema() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestActivationMethodsResponseSchema" /> class.
        /// </summary>
        /// <param name="responseId">The id of the response sent. (required).</param>
        /// <param name="activationMethods">The activation methods to be used for this digitization. Return empty array if no methods are to be returned. Max length - Not applicable. Type - Array [ActivationMethod]. Required..</param>
        public RequestActivationMethodsResponseSchema(string responseId = default(string), List<ActivationMethod> activationMethods = default(List<ActivationMethod>))
        {
            // to ensure "responseId" is required (not null)
            if (responseId == null)
            {
                throw new ArgumentNullException("responseId is a required property for RequestActivationMethodsResponseSchema and cannot be null");
            }
            this.responseId = responseId;
            this.activationMethods = activationMethods;
        }

        /// <summary>
        /// The id of the response sent.
        /// </summary>
        /// <value>The id of the response sent.</value>
        /// <example>123456</example>
        [DataMember(Name = "responseId", IsRequired = true, EmitDefaultValue = true)]
        public string responseId { get; set; }

        /// <summary>
        /// The activation methods to be used for this digitization. Return empty array if no methods are to be returned. Max length - Not applicable. Type - Array [ActivationMethod]. Required.
        /// </summary>
        /// <value>The activation methods to be used for this digitization. Return empty array if no methods are to be returned. Max length - Not applicable. Type - Array [ActivationMethod]. Required.</value>
        [DataMember(Name = "activationMethods", EmitDefaultValue = false)]
        public List<ActivationMethod> activationMethods { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RequestActivationMethodsResponseSchema {\n");
            sb.Append("  responseId: ").Append(responseId).Append("\n");
            sb.Append("  activationMethods: ").Append(activationMethods).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // responseId (string) maxLength
            if (this.responseId != null && this.responseId.Length > 64)
            {
                yield return new ValidationResult("Invalid value for responseId, length must be less than 64.", new [] { "responseId" });
            }

            // responseId (string) minLength
            if (this.responseId != null && this.responseId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for responseId, length must be greater than 1.", new [] { "responseId" });
            }

            yield break;
        }
    }

}
