/*
 * Mastercard Digital Enablement API
 *
 * The Mastercard Digital Enablement API encompasses a set of APIs that are initiated by the Token Requestor for the purposes of creating and managing the life cycle of a token.      **Authentication**  <br><br>  Mastercard uses OAuth 1.0a with body hash extension for authenticating the API clients. This requires every request that you send to  Mastercard to be signed with an RSA private key. A private-public RSA key pair must be generated consisting of:  <br><br>  1. A private key for the OAuth signature for API requests. It is recommended to keep the private key in a password-protected or hardware keystore.  <br>  2. A public key is shared with Mastercard during the project setup process through either a certificate signing request (CSR) or the API Key Generator. Mastercard will use the public key to verify the OAuth signature that is provided on every API call.<br>   An OAUTH1.0a signer library is available on [GitHub](https://github.com/Mastercard/oauth1-signer-java)  <br><br>  **Encryption**  <br><br>  All communications between Issuer web service and the Mastercard gateway is encrypted using TLS.  <br><br>  **Additional Encryption of Sensitive Data**  <br><br>  In addition to the OAuth authentication, when using MDES Digital Enablement Service, any PCI sensitive and all account holder Personally Identifiable Information (PII) data must be encrypted. This requirement applies to the API fields containing encryptedData. Sensitive data is encrypted using a symmetric session (one-time-use) key. The symmetric session key is then wrapped with an RSA Public Key supplied by Mastercard during API setup phase (the Customer Encryption Key). <br>   Java Client Encryption Library available on [GitHub](https://github.com/Mastercard/client-encryption-java) 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SearchTokens
    /// </summary>
    [DataContract(Name = "SearchTokens")]
    public partial class SearchTokens : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchTokens" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchTokens() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchTokens" /> class.
        /// </summary>
        /// <param name="requestId">Unique identifier for the request.  (required).</param>
        /// <param name="responseHost">The host that originated the request. Future calls in the same conversation may be routed to this host. .</param>
        /// <param name="fundingAccountInfo">fundingAccountInfo.</param>
        /// <param name="tokenRequestorId">Identifies the Token Requestor. Only tokens associated with the token requestor will be returned. .</param>
        public SearchTokens(string requestId = default(string), string responseHost = default(string), FundingAccountInfo fundingAccountInfo = default(FundingAccountInfo), string tokenRequestorId = default(string))
        {
            // to ensure "requestId" is required (not null)
            if (requestId == null)
            {
                throw new ArgumentNullException("requestId is a required property for SearchTokens and cannot be null");
            }
            this.RequestId = requestId;
            this.ResponseHost = responseHost;
            this.FundingAccountInfo = fundingAccountInfo;
            this.TokenRequestorId = tokenRequestorId;
        }

        /// <summary>
        /// Unique identifier for the request. 
        /// </summary>
        /// <value>Unique identifier for the request. </value>
        /// <example>123456</example>
        [DataMember(Name = "requestId", IsRequired = true, EmitDefaultValue = true)]
        public string RequestId { get; set; }

        /// <summary>
        /// The host that originated the request. Future calls in the same conversation may be routed to this host. 
        /// </summary>
        /// <value>The host that originated the request. Future calls in the same conversation may be routed to this host. </value>
        /// <example>site2.payment-app-provider.com</example>
        [DataMember(Name = "responseHost", EmitDefaultValue = false)]
        public string ResponseHost { get; set; }

        /// <summary>
        /// Gets or Sets FundingAccountInfo
        /// </summary>
        [DataMember(Name = "fundingAccountInfo", EmitDefaultValue = false)]
        public FundingAccountInfo FundingAccountInfo { get; set; }

        /// <summary>
        /// Identifies the Token Requestor. Only tokens associated with the token requestor will be returned. 
        /// </summary>
        /// <value>Identifies the Token Requestor. Only tokens associated with the token requestor will be returned. </value>
        /// <example>98765432101</example>
        [DataMember(Name = "tokenRequestorId", EmitDefaultValue = false)]
        public string TokenRequestorId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchTokens {\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  ResponseHost: ").Append(ResponseHost).Append("\n");
            sb.Append("  FundingAccountInfo: ").Append(FundingAccountInfo).Append("\n");
            sb.Append("  TokenRequestorId: ").Append(TokenRequestorId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RequestId (string) maxLength
            if (this.RequestId != null && this.RequestId.Length > 64)
            {
                yield return new ValidationResult("Invalid value for RequestId, length must be less than 64.", new [] { "RequestId" });
            }

            // RequestId (string) minLength
            if (this.RequestId != null && this.RequestId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for RequestId, length must be greater than 1.", new [] { "RequestId" });
            }

            // ResponseHost (string) maxLength
            if (this.ResponseHost != null && this.ResponseHost.Length > 64)
            {
                yield return new ValidationResult("Invalid value for ResponseHost, length must be less than 64.", new [] { "ResponseHost" });
            }

            // ResponseHost (string) minLength
            if (this.ResponseHost != null && this.ResponseHost.Length < 11)
            {
                yield return new ValidationResult("Invalid value for ResponseHost, length must be greater than 11.", new [] { "ResponseHost" });
            }

            // TokenRequestorId (string) maxLength
            if (this.TokenRequestorId != null && this.TokenRequestorId.Length > 11)
            {
                yield return new ValidationResult("Invalid value for TokenRequestorId, length must be less than 11.", new [] { "TokenRequestorId" });
            }

            // TokenRequestorId (string) minLength
            if (this.TokenRequestorId != null && this.TokenRequestorId.Length < 11)
            {
                yield return new ValidationResult("Invalid value for TokenRequestorId, length must be greater than 11.", new [] { "TokenRequestorId" });
            }

            yield break;
        }
    }

}
