/*
 * Mastercard Digital Enablement API
 *
 * The Mastercard Digital Enablement API encompasses a set of APIs that are initiated by the Token Requestor for the purposes of creating and managing the life cycle of a token.      **Authentication**  <br><br>  Mastercard uses OAuth 1.0a with body hash extension for authenticating the API clients. This requires every request that you send to  Mastercard to be signed with an RSA private key. A private-public RSA key pair must be generated consisting of:  <br><br>  1. A private key for the OAuth signature for API requests. It is recommended to keep the private key in a password-protected or hardware keystore.  <br>  2. A public key is shared with Mastercard during the project setup process through either a certificate signing request (CSR) or the API Key Generator. Mastercard will use the public key to verify the OAuth signature that is provided on every API call.<br>   An OAUTH1.0a signer library is available on [GitHub](https://github.com/Mastercard/oauth1-signer-java)  <br><br>  **Encryption**  <br><br>  All communications between Issuer web service and the Mastercard gateway is encrypted using TLS.  <br><br>  **Additional Encryption of Sensitive Data**  <br><br>  In addition to the OAuth authentication, when using MDES Digital Enablement Service, any PCI sensitive and all account holder Personally Identifiable Information (PII) data must be encrypted. This requirement applies to the API fields containing encryptedData. Sensitive data is encrypted using a symmetric session (one-time-use) key. The symmetric session key is then wrapped with an RSA Public Key supplied by Mastercard during API setup phase (the Customer Encryption Key). <br>   Java Client Encryption Library available on [GitHub](https://github.com/Mastercard/client-encryption-java) 
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TokenDetailDataGetTokenOnly
    /// </summary>
    [DataContract(Name = "tokenDetailData_getToken_Only")]
    public partial class TokenDetailDataGetTokenOnly : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TokenDetailDataGetTokenOnly" /> class.
        /// </summary>
        /// <param name="tokenNumber">The Token Primary Account Number of the Card. .</param>
        /// <param name="expiryMonth">The month of the token expiration date. .</param>
        /// <param name="expiryYear">The year of the token expiration date. .</param>
        /// <param name="paymentAccountReference">The unique account reference assigned to the PAN. Conditionally returned if the Token Requestor has opted to receive PAR and providing PAR is assigned by Mastercard or the Issuer provides PAR in the authorization message response. .</param>
        public TokenDetailDataGetTokenOnly(string tokenNumber = default(string), string expiryMonth = default(string), string expiryYear = default(string), string paymentAccountReference = default(string))
        {
            this.TokenNumber = tokenNumber;
            this.ExpiryMonth = expiryMonth;
            this.ExpiryYear = expiryYear;
            this.PaymentAccountReference = paymentAccountReference;
        }

        /// <summary>
        /// The Token Primary Account Number of the Card. 
        /// </summary>
        /// <value>The Token Primary Account Number of the Card. </value>
        /// <example>5123456789012345</example>
        [DataMember(Name = "tokenNumber", EmitDefaultValue = false)]
        public string TokenNumber { get; set; }

        /// <summary>
        /// The month of the token expiration date. 
        /// </summary>
        /// <value>The month of the token expiration date. </value>
        /// <example>12</example>
        [DataMember(Name = "expiryMonth", EmitDefaultValue = false)]
        public string ExpiryMonth { get; set; }

        /// <summary>
        /// The year of the token expiration date. 
        /// </summary>
        /// <value>The year of the token expiration date. </value>
        /// <example>18</example>
        [DataMember(Name = "expiryYear", EmitDefaultValue = false)]
        public string ExpiryYear { get; set; }

        /// <summary>
        /// The unique account reference assigned to the PAN. Conditionally returned if the Token Requestor has opted to receive PAR and providing PAR is assigned by Mastercard or the Issuer provides PAR in the authorization message response. 
        /// </summary>
        /// <value>The unique account reference assigned to the PAN. Conditionally returned if the Token Requestor has opted to receive PAR and providing PAR is assigned by Mastercard or the Issuer provides PAR in the authorization message response. </value>
        /// <example>5001a9f027e5629d11e3949a0800a</example>
        [DataMember(Name = "paymentAccountReference", EmitDefaultValue = false)]
        public string PaymentAccountReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TokenDetailDataGetTokenOnly {\n");
            sb.Append("  TokenNumber: ").Append(TokenNumber).Append("\n");
            sb.Append("  ExpiryMonth: ").Append(ExpiryMonth).Append("\n");
            sb.Append("  ExpiryYear: ").Append(ExpiryYear).Append("\n");
            sb.Append("  PaymentAccountReference: ").Append(PaymentAccountReference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TokenNumber (string) maxLength
            if (this.TokenNumber != null && this.TokenNumber.Length > 19)
            {
                yield return new ValidationResult("Invalid value for TokenNumber, length must be less than 19.", new [] { "TokenNumber" });
            }

            // TokenNumber (string) minLength
            if (this.TokenNumber != null && this.TokenNumber.Length < 9)
            {
                yield return new ValidationResult("Invalid value for TokenNumber, length must be greater than 9.", new [] { "TokenNumber" });
            }

            // ExpiryMonth (string) maxLength
            if (this.ExpiryMonth != null && this.ExpiryMonth.Length > 2)
            {
                yield return new ValidationResult("Invalid value for ExpiryMonth, length must be less than 2.", new [] { "ExpiryMonth" });
            }

            // ExpiryMonth (string) minLength
            if (this.ExpiryMonth != null && this.ExpiryMonth.Length < 2)
            {
                yield return new ValidationResult("Invalid value for ExpiryMonth, length must be greater than 2.", new [] { "ExpiryMonth" });
            }

            // ExpiryYear (string) maxLength
            if (this.ExpiryYear != null && this.ExpiryYear.Length > 2)
            {
                yield return new ValidationResult("Invalid value for ExpiryYear, length must be less than 2.", new [] { "ExpiryYear" });
            }

            // ExpiryYear (string) minLength
            if (this.ExpiryYear != null && this.ExpiryYear.Length < 2)
            {
                yield return new ValidationResult("Invalid value for ExpiryYear, length must be greater than 2.", new [] { "ExpiryYear" });
            }

            // PaymentAccountReference (string) maxLength
            if (this.PaymentAccountReference != null && this.PaymentAccountReference.Length > 29)
            {
                yield return new ValidationResult("Invalid value for PaymentAccountReference, length must be less than 29.", new [] { "PaymentAccountReference" });
            }

            // PaymentAccountReference (string) minLength
            if (this.PaymentAccountReference != null && this.PaymentAccountReference.Length < 29)
            {
                yield return new ValidationResult("Invalid value for PaymentAccountReference, length must be greater than 29.", new [] { "PaymentAccountReference" });
            }

            yield break;
        }
    }

}
