/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AccountHolderDataSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountHolderDataSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountHolderDataSchema
        //private AccountHolderDataSchema instance;

        public AccountHolderDataSchemaTests()
        {
            // TODO uncomment below to create an instance of AccountHolderDataSchema
            //instance = new AccountHolderDataSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountHolderDataSchema
        /// </summary>
        [Fact]
        public void AccountHolderDataSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountHolderDataSchema
            //Assert.IsType<AccountHolderDataSchema>(instance);
        }

        /// <summary>
        /// Test the property 'accountHolderName'
        /// </summary>
        [Fact]
        public void accountHolderNameTest()
        {
            // TODO unit test for the property 'accountHolderName'
        }

        /// <summary>
        /// Test the property 'accountHolderAddress'
        /// </summary>
        [Fact]
        public void accountHolderAddressTest()
        {
            // TODO unit test for the property 'accountHolderAddress'
        }

        /// <summary>
        /// Test the property 'sourceIp'
        /// </summary>
        [Fact]
        public void sourceIpTest()
        {
            // TODO unit test for the property 'sourceIp'
        }

        /// <summary>
        /// Test the property 'deviceLocation'
        /// </summary>
        [Fact]
        public void deviceLocationTest()
        {
            // TODO unit test for the property 'deviceLocation'
        }

        /// <summary>
        /// Test the property 'consumerIdentifier'
        /// </summary>
        [Fact]
        public void consumerIdentifierTest()
        {
            // TODO unit test for the property 'consumerIdentifier'
        }

        /// <summary>
        /// Test the property 'accountHolderEmailAddress'
        /// </summary>
        [Fact]
        public void accountHolderEmailAddressTest()
        {
            // TODO unit test for the property 'accountHolderEmailAddress'
        }

        /// <summary>
        /// Test the property 'accountHolderMobilePhoneNumber'
        /// </summary>
        [Fact]
        public void accountHolderMobilePhoneNumberTest()
        {
            // TODO unit test for the property 'accountHolderMobilePhoneNumber'
        }
    }
}
