/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;


using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AuthorizeServiceResponseDataSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthorizeServiceResponseDataSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthorizeServiceResponseDataSchema
        //private AuthorizeServiceResponseDataSchema instance;

        public AuthorizeServiceResponseDataSchemaTests()
        {
            // TODO uncomment below to create an instance of AuthorizeServiceResponseDataSchema
            //instance = new AuthorizeServiceResponseDataSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthorizeServiceResponseDataSchema
        /// </summary>
        [Fact]
        public void AuthorizeServiceResponseDataSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthorizeServiceResponseDataSchema
            //Assert.IsType<AuthorizeServiceResponseDataSchema>(instance);
        }

        /// <summary>
        /// Test the property 'dataValidUntilTimestamp'
        /// </summary>
        [Fact]
        public void dataValidUntilTimestampTest()
        {
            // TODO unit test for the property 'dataValidUntilTimestamp'
        }

        /// <summary>
        /// Test the property 'paymentAccountReference'
        /// </summary>
        [Fact]
        public void paymentAccountReferenceTest()
        {
            // TODO unit test for the property 'paymentAccountReference'
        }

        /// <summary>
        /// Test the property 'alternateAccountIdentifier'
        /// </summary>
        [Fact]
        public void alternateAccountIdentifierTest()
        {
            // TODO unit test for the property 'alternateAccountIdentifier'
        }

        /// <summary>
        /// Test the property 'issuerSpecificPersonalizationData'
        /// </summary>
        [Fact]
        public void issuerSpecificPersonalizationDataTest()
        {
            // TODO unit test for the property 'issuerSpecificPersonalizationData'
        }

        /// <summary>
        /// Test the property 'externalToken'
        /// </summary>
        [Fact]
        public void externalTokenTest()
        {
            // TODO unit test for the property 'externalToken'
        }
    }
}
