/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;


using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing BillingAddressSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BillingAddressSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BillingAddressSchema
        //private BillingAddressSchema instance;

        public BillingAddressSchemaTests()
        {
            // TODO uncomment below to create an instance of BillingAddressSchema
            //instance = new BillingAddressSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BillingAddressSchema
        /// </summary>
        [Fact]
        public void BillingAddressSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" BillingAddressSchema
            //Assert.IsType<BillingAddressSchema>(instance);
        }

        /// <summary>
        /// Test the property 'line1'
        /// </summary>
        [Fact]
        public void line1Test()
        {
            // TODO unit test for the property 'line1'
        }

        /// <summary>
        /// Test the property 'line2'
        /// </summary>
        [Fact]
        public void line2Test()
        {
            // TODO unit test for the property 'line2'
        }

        /// <summary>
        /// Test the property 'city'
        /// </summary>
        [Fact]
        public void cityTest()
        {
            // TODO unit test for the property 'city'
        }

        /// <summary>
        /// Test the property 'countrySubdivision'
        /// </summary>
        [Fact]
        public void countrySubdivisionTest()
        {
            // TODO unit test for the property 'countrySubdivision'
        }

        /// <summary>
        /// Test the property 'postalCode'
        /// </summary>
        [Fact]
        public void postalCodeTest()
        {
            // TODO unit test for the property 'postalCode'
        }

        /// <summary>
        /// Test the property 'country'
        /// </summary>
        [Fact]
        public void countryTest()
        {
            // TODO unit test for the property 'country'
        }
    }
}
