/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;


using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CardAccountDataSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardAccountDataSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CardAccountDataSchema
        //private CardAccountDataSchema instance;

        public CardAccountDataSchemaTests()
        {
            // TODO uncomment below to create an instance of CardAccountDataSchema
            //instance = new CardAccountDataSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CardAccountDataSchema
        /// </summary>
        [Fact]
        public void CardAccountDataSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" CardAccountDataSchema
            //Assert.IsType<CardAccountDataSchema>(instance);
        }

        /// <summary>
        /// Test the property 'accountNumber'
        /// </summary>
        [Fact]
        public void accountNumberTest()
        {
            // TODO unit test for the property 'accountNumber'
        }

        /// <summary>
        /// Test the property 'expiryMonth'
        /// </summary>
        [Fact]
        public void expiryMonthTest()
        {
            // TODO unit test for the property 'expiryMonth'
        }

        /// <summary>
        /// Test the property 'expiryYear'
        /// </summary>
        [Fact]
        public void expiryYearTest()
        {
            // TODO unit test for the property 'expiryYear'
        }

        /// <summary>
        /// Test the property 'securityCode'
        /// </summary>
        [Fact]
        public void securityCodeTest()
        {
            // TODO unit test for the property 'securityCode'
        }
    }
}
