/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;


using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceInfo
        //private DeviceInfo instance;

        public DeviceInfoTests()
        {
            // TODO uncomment below to create an instance of DeviceInfo
            //instance = new DeviceInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceInfo
        /// </summary>
        [Fact]
        public void DeviceInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceInfo
            //Assert.IsType<DeviceInfo>(instance);
        }

        /// <summary>
        /// Test the property 'deviceName'
        /// </summary>
        [Fact]
        public void deviceNameTest()
        {
            // TODO unit test for the property 'deviceName'
        }

        /// <summary>
        /// Test the property 'serialNumber'
        /// </summary>
        [Fact]
        public void serialNumberTest()
        {
            // TODO unit test for the property 'serialNumber'
        }

        /// <summary>
        /// Test the property 'formFactor'
        /// </summary>
        [Fact]
        public void formFactorTest()
        {
            // TODO unit test for the property 'formFactor'
        }

        /// <summary>
        /// Test the property 'isoDeviceType'
        /// </summary>
        [Fact]
        public void isoDeviceTypeTest()
        {
            // TODO unit test for the property 'isoDeviceType'
        }

        /// <summary>
        /// Test the property 'osName'
        /// </summary>
        [Fact]
        public void osNameTest()
        {
            // TODO unit test for the property 'osName'
        }

        /// <summary>
        /// Test the property 'osVersion'
        /// </summary>
        [Fact]
        public void osVersionTest()
        {
            // TODO unit test for the property 'osVersion'
        }

        /// <summary>
        /// Test the property 'imei'
        /// </summary>
        [Fact]
        public void imeiTest()
        {
            // TODO unit test for the property 'imei'
        }

        /// <summary>
        /// Test the property 'msisdn'
        /// </summary>
        [Fact]
        public void msisdnTest()
        {
            // TODO unit test for the property 'msisdn'
        }

        /// <summary>
        /// Test the property 'paymentTypes'
        /// </summary>
        [Fact]
        public void paymentTypesTest()
        {
            // TODO unit test for the property 'paymentTypes'
        }

        /// <summary>
        /// Test the property 'storageTechnology'
        /// </summary>
        [Fact]
        public void storageTechnologyTest()
        {
            // TODO unit test for the property 'storageTechnology'
        }

        /// <summary>
        /// Test the property 'cardCaptureTechnology'
        /// </summary>
        [Fact]
        public void cardCaptureTechnologyTest()
        {
            // TODO unit test for the property 'cardCaptureTechnology'
        }
    }
}
