/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;


using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EncryptedPayloadSchemaForNTU
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EncryptedPayloadSchemaForNTUTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EncryptedPayloadSchemaForNTU
        //private EncryptedPayloadSchemaForNTU instance;

        public EncryptedPayloadSchemaForNTUTests()
        {
            // TODO uncomment below to create an instance of EncryptedPayloadSchemaForNTU
            //instance = new EncryptedPayloadSchemaForNTU();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EncryptedPayloadSchemaForNTU
        /// </summary>
        [Fact]
        public void EncryptedPayloadSchemaForNTUInstanceTest()
        {
            // TODO uncomment below to test "IsType" EncryptedPayloadSchemaForNTU
            //Assert.IsType<EncryptedPayloadSchemaForNTU>(instance);
        }

        /// <summary>
        /// Test the property 'encryptedData'
        /// </summary>
        [Fact]
        public void encryptedDataTest()
        {
            // TODO unit test for the property 'encryptedData'
        }

        /// <summary>
        /// Test the property 'publicKeyFingerprint'
        /// </summary>
        [Fact]
        public void publicKeyFingerprintTest()
        {
            // TODO unit test for the property 'publicKeyFingerprint'
        }

        /// <summary>
        /// Test the property 'encryptedKey'
        /// </summary>
        [Fact]
        public void encryptedKeyTest()
        {
            // TODO unit test for the property 'encryptedKey'
        }

        /// <summary>
        /// Test the property 'oaepHashingAlgorithm'
        /// </summary>
        [Fact]
        public void oaepHashingAlgorithmTest()
        {
            // TODO unit test for the property 'oaepHashingAlgorithm'
        }

        /// <summary>
        /// Test the property 'iv'
        /// </summary>
        [Fact]
        public void ivTest()
        {
            // TODO unit test for the property 'iv'
        }
    }
}
