/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;


using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing FundingAccountInfoSchema1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FundingAccountInfoSchema1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FundingAccountInfoSchema1
        //private FundingAccountInfoSchema1 instance;

        public FundingAccountInfoSchema1Tests()
        {
            // TODO uncomment below to create an instance of FundingAccountInfoSchema1
            //instance = new FundingAccountInfoSchema1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FundingAccountInfoSchema1
        /// </summary>
        [Fact]
        public void FundingAccountInfoSchema1InstanceTest()
        {
            // TODO uncomment below to test "IsType" FundingAccountInfoSchema1
            //Assert.IsType<FundingAccountInfoSchema1>(instance);
        }

        /// <summary>
        /// Test the property 'tokenUniqueReference'
        /// </summary>
        [Fact]
        public void tokenUniqueReferenceTest()
        {
            // TODO unit test for the property 'tokenUniqueReference'
        }

        /// <summary>
        /// Test the property 'panUniqueReference'
        /// </summary>
        [Fact]
        public void panUniqueReferenceTest()
        {
            // TODO unit test for the property 'panUniqueReference'
        }

        /// <summary>
        /// Test the property 'encryptedPayload'
        /// </summary>
        [Fact]
        public void encryptedPayloadTest()
        {
            // TODO unit test for the property 'encryptedPayload'
        }
    }
}
