/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;


using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing FundingAccountDataSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FundingAccountDataSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FundingAccountDataSchema
        //private FundingAccountDataSchema instance;

        public FundingAccountDataSchemaTests()
        {
            // TODO uncomment below to create an instance of FundingAccountDataSchema
            //instance = new FundingAccountDataSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FundingAccountDataSchema
        /// </summary>
        [Fact]
        public void FundingAccountDataSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" FundingAccountDataSchema
            //Assert.IsType<FundingAccountDataSchema>(instance);
        }

        /// <summary>
        /// Test the property 'source'
        /// </summary>
        [Fact]
        public void sourceTest()
        {
            // TODO unit test for the property 'source'
        }

        /// <summary>
        /// Test the property 'dataValidUntilTimestamp'
        /// </summary>
        [Fact]
        public void dataValidUntilTimestampTest()
        {
            // TODO unit test for the property 'dataValidUntilTimestamp'
        }

        /// <summary>
        /// Test the property 'cardAccountData'
        /// </summary>
        [Fact]
        public void cardAccountDataTest()
        {
            // TODO unit test for the property 'cardAccountData'
        }

        /// <summary>
        /// Test the property 'financialAccountData'
        /// </summary>
        [Fact]
        public void financialAccountDataTest()
        {
            // TODO unit test for the property 'financialAccountData'
        }

        /// <summary>
        /// Test the property 'tokenData'
        /// </summary>
        [Fact]
        public void tokenDataTest()
        {
            // TODO unit test for the property 'tokenData'
        }

        /// <summary>
        /// Test the property 'paymentAccountReference'
        /// </summary>
        [Fact]
        public void paymentAccountReferenceTest()
        {
            // TODO unit test for the property 'paymentAccountReference'
        }

        /// <summary>
        /// Test the property 'accountHolderData'
        /// </summary>
        [Fact]
        public void accountHolderDataTest()
        {
            // TODO unit test for the property 'accountHolderData'
        }

        /// <summary>
        /// Test the property 'chipData'
        /// </summary>
        [Fact]
        public void chipDataTest()
        {
            // TODO unit test for the property 'chipData'
        }
    }
}
