/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;


using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing NotifyTokenUpdatedRequestSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotifyTokenUpdatedRequestSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NotifyTokenUpdatedRequestSchema
        //private NotifyTokenUpdatedRequestSchema instance;

        public NotifyTokenUpdatedRequestSchemaTests()
        {
            // TODO uncomment below to create an instance of NotifyTokenUpdatedRequestSchema
            //instance = new NotifyTokenUpdatedRequestSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotifyTokenUpdatedRequestSchema
        /// </summary>
        [Fact]
        public void NotifyTokenUpdatedRequestSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" NotifyTokenUpdatedRequestSchema
            //Assert.IsType<NotifyTokenUpdatedRequestSchema>(instance);
        }

        /// <summary>
        /// Test the property 'requestId'
        /// </summary>
        [Fact]
        public void requestIdTest()
        {
            // TODO unit test for the property 'requestId'
        }

        /// <summary>
        /// Test the property 'reasonCode'
        /// </summary>
        [Fact]
        public void reasonCodeTest()
        {
            // TODO unit test for the property 'reasonCode'
        }

        /// <summary>
        /// Test the property 'tokens'
        /// </summary>
        [Fact]
        public void tokensTest()
        {
            // TODO unit test for the property 'tokens'
        }
    }
}
