/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. All request and response parameters are case sensitive. 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PushAccountSignatureData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PushAccountSignatureDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PushAccountSignatureData
        //private PushAccountSignatureData instance;

        public PushAccountSignatureDataTests()
        {
            // TODO uncomment below to create an instance of PushAccountSignatureData
            //instance = new PushAccountSignatureData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PushAccountSignatureData
        /// </summary>
        [Fact]
        public void PushAccountSignatureDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" PushAccountSignatureData
            //Assert.IsType<PushAccountSignatureData>(instance);
        }

        /// <summary>
        /// Test the property 'callbackURL'
        /// </summary>
        [Fact]
        public void callbackURLTest()
        {
            // TODO unit test for the property 'callbackURL'
        }

        /// <summary>
        /// Test the property 'completeIssuerAppActivation'
        /// </summary>
        [Fact]
        public void completeIssuerAppActivationTest()
        {
            // TODO unit test for the property 'completeIssuerAppActivation'
        }

        /// <summary>
        /// Test the property 'completeWebsiteActivation'
        /// </summary>
        [Fact]
        public void completeWebsiteActivationTest()
        {
            // TODO unit test for the property 'completeWebsiteActivation'
        }

        /// <summary>
        /// Test the property 'accountHolderDataSupplied'
        /// </summary>
        [Fact]
        public void accountHolderDataSuppliedTest()
        {
            // TODO unit test for the property 'accountHolderDataSupplied'
        }

        /// <summary>
        /// Test the property 'locale'
        /// </summary>
        [Fact]
        public void localeTest()
        {
            // TODO unit test for the property 'locale'
        }
    }
}
