/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. All request and response parameters are case sensitive. 
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PushMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PushMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PushMethod
        //private PushMethod instance;

        public PushMethodTests()
        {
            // TODO uncomment below to create an instance of PushMethod
            //instance = new PushMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PushMethod
        /// </summary>
        [Fact]
        public void PushMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" PushMethod
            //Assert.IsType<PushMethod>(instance);
        }

        /// <summary>
        /// Test the property 'type'
        /// </summary>
        [Fact]
        public void typeTest()
        {
            // TODO unit test for the property 'type'
        }

        /// <summary>
        /// Test the property 'uri'
        /// </summary>
        [Fact]
        public void uriTest()
        {
            // TODO unit test for the property 'uri'
        }
    }
}
