/*
 * Mastercard Digital Enablement Service Issuer Outbound API
 *
 * The MDES Issuer Outbound Pre-Digitization API supports the pre-digitization web services provided by the Digitization Service. The web services are used to inform Issuers of MDES services being requested by, or on-behalf of, their account holders. Issuers may provide information in their responses to guide or inform the Account holder’s experience through the Token Reqestor.
 *
 * The version of the OpenAPI document: 2.0.21 (Document version)
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;


using System.Reflection;
using Newtonsoft.Json;

namespace Acme.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SystemAtcStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SystemAtcStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SystemAtcStatus
        //private SystemAtcStatus instance;

        public SystemAtcStatusTests()
        {
            // TODO uncomment below to create an instance of SystemAtcStatus
            //instance = new SystemAtcStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SystemAtcStatus
        /// </summary>
        [Fact]
        public void SystemAtcStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" SystemAtcStatus
            //Assert.IsType<SystemAtcStatus>(instance);
        }

        /// <summary>
        /// Test the property 'atcNotFound'
        /// </summary>
        [Fact]
        public void atcNotFoundTest()
        {
            // TODO unit test for the property 'atcNotFound'
        }

        /// <summary>
        /// Test the property 'atcAlreadyProcessed'
        /// </summary>
        [Fact]
        public void atcAlreadyProcessedTest()
        {
            // TODO unit test for the property 'atcAlreadyProcessed'
        }

        /// <summary>
        /// Test the property 'atcReportedUsedByWallet'
        /// </summary>
        [Fact]
        public void atcReportedUsedByWalletTest()
        {
            // TODO unit test for the property 'atcReportedUsedByWallet'
        }

        /// <summary>
        /// Test the property 'unusedActive'
        /// </summary>
        [Fact]
        public void unusedActiveTest()
        {
            // TODO unit test for the property 'unusedActive'
        }
    }
}
